version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt -r requirements-dev.txt
			- save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
				paths:
					- pip
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: mamba
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
